### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Reeeemi** [AdaCore/gnatcoll-core#24]
Hi,

I'm trying to install gnatcoll-core as I need it to be able to install GNATCoverage. However, when building, I get the following error:

`gnatcoll-projects.adb:5005:23: "Expression" not declared in "Proc"`

I have been trying to figure this out for a day now, but I can't get it to work.

How I'm trying to build:

1. Extract gnatcoll-core zip
2. Execute `make setup`
3. Execute `make`. This is were the error occurs.

Maybe it's a version incompatability, so here's my GNAT and GPRbuild version:

My GNAT version: GNAT GPL 2017 (20170515-63)
My GPRbuild version: GPRBUILD GPL 2017 (20170515) (x86_64-pc-linux-gnu)

Thanks in advance

**Comment by pmderodat** [comment]
Hello @Reeeemi ,

[Libgpr](https://github.com/AdaCore/gprbuild/) is a dependency for GNATCOLL. It is likely that `gnatcoll-core`’s `master` branch depends on recent Libgpr changes, and that these changes are not included in pre-built Libgpr that is included in GNAT GPL 2017. Because of this, I think you would need to re-build and install Libgpr yourself before attempting to build GNATCOLL.

However, first: have you tried building GNATcoverage using the GNATCOLL that is also built-in GNAT GPL 2017? (i.e. without rebuilding your own GNATCOLL) That worked just fine on my machine, so this would be the easiest way. Note that you will need the following patch for the GNATcoverage’s `master` branch to build with GNAT GPL 2017:

```
diff --git a/tools/gnatcov/sc_obligations.ads b/tools/gnatcov/sc_obligations.ads
index 98e7a6ea..08813b3e 100644
--- a/tools/gnatcov/sc_obligations.ads
+++ b/tools/gnatcov/sc_obligations.ads
@@ -333,7 +333,6 @@ private
           Pragma_Ada_2005 => False,
           Pragma_Ada_12 => False,
           Pragma_Ada_2012 => False,
-          Pragma_Ada_2020 => False,
 
           Pragma_Allow_Integer_Address => False,
           Pragma_Annotate => False,
```

This is needed because GNATcoverage’s `master` branch (i.e. development version) is synchronized with GNAT’s development version.
