### ISSUE TITLE
GNATCOLL.JSON: allow unquoted strings

### ISSUE THREAD

**Issue by briot** [AdaCore/gnatcoll-core#33]
We want to use a JSON-like format for a configuration file. Unfortunately, JSON is quite heavy to use because it requires all strings to be quoted (in particular if you writing the config as an Ada string).

I would like to propose a patch which allows unquoted strings when they only contain [a-zA-Z0-9_]
characters, like Ada identifiers, and are not "null", "true" or "false" which already have special meaning.
This behavior is controlled by a new "Options" parameter to Parse, so that users can decide to opt-in.

We would also like to support comments, using "#", and also under control of Options.

Such a change is compatible with a well known JSON extension, namely YAML. Supporting full YAML is a more significant project which we don't have time to implement.

Is that an idea that could be useful to GNATCOLL ?

**Comment by pmderodat** [comment]
Adding some non-standard extension to `GNATCOLL.JSON` does not look very appealing: it’s important to keep the parser reject inputs that don’t respect the JSON standard. We could start adding options to disable the handling of such extensions by default, but that road seems complex both in terms of code and in terms of testing.

If your goal is to use a lighter syntax, YAML indeed seems the way to go. You don’t have to re-write your own YAML parser in GNATCOLL: have you investigated using something like [AdaYaml](https://github.com/yaml/AdaYaml)?

**Comment by briot** [comment]
Of course these extensions are under control of flags, and not accepted by default.
The reason I did not want to use AdaYaml are twofold: this is a large library, and is not usable from GNATCOLL. The goal here was to change the format of the configuration file for GNATCOLL.Traces (or rather for a newer version we made and hope to contribute at some point), so I needed a simple parser that could be used from GNATCOLL.

Unfortunately, I did not find a way to implement those extensions from outside of GNATCOLL.JSON itself (in the sense: find minimal changes to JSON to provide hooks for this).

**Comment by pmderodat** [comment]
Ok, thank you for the context.

As I said, we’d rather avoid introducing extensions in the JSON parser, especially if it’s just as a workaround for not having a YAML parser in GNATCOLL.

Regarding the actual goal of changing the configuration format for `GNATCOLL.Traces`, that’s definitely something we don’t want (breaking change!). Also, what if someone wants later an XML configuration? or a TOML syntax? This got me thinking: what about instead exposing a configuration API? (rather than just a language) Anyone would then be able to create custom configuration DSLs on top of that outside of GNATCOLL: YAML, XML or whatever. The current syntax could be re-implemented on top of this API for backwards compatibility.

What do you think?

**Comment by briot** [comment]
> Regarding the actual goal of changing the configuration format for GNATCOLL.Traces, that’s definitely something we don’t want (breaking change!). Also, what if someone wants later an XML configuration? or a TOML syntax? This got me thinking: what about instead exposing a configuration API? (rather than just a language) Anyone would then be able to create custom configuration DSLs on top of that outside of GNATCOLL: YAML, XML or whatever. The current syntax could be re-implemented on top of this API for backwards compatibility.


I am not planning on changing anything in GNATCOLL.Traces.
There’s no way to improve things that while staying backward compatible, so instead we have a 
separate package. 
Inactive traces cost 3ns whatever the message (vs 3us with GNATCOLL.Traces).
active traces are about twice 3 times as fast in synchronous mode, and we now support a
non-blocking asynchronous modes. Messages can be sent to multiple streams,..
All things that cannot added to GNATCOLL.Traces, also in particular because of the ad-hoc
configuration file.

I am not sure what you call a configuration API. Basically, in our package, everything can be done
directly via code (via various setters and factories), so anyone can indeed have their own
configuration layer that calls those setters. But out of the box the package needs to come with
at least one such format, for convenience.

Just as in GNATCOLL.Traces, it is convenient to be able to initialize loggers with some hard-coded
config, and then let users override those defaults via a config file. The code looks like:

   Config : constant String := “…”;
   Parse_Config (Config);
   Parse_Config_File (“.gnatdebug”);

For the config, writing JSON in Ada is… unmanageable. For instance:

   Config : constant String := “{“ & 
      “””loggers””: {“ &
         “””name””: {…}” &
     “}}”;

Whereas if we allow unquoted strings in simple cases, we have the simpler:

   Config : constant String := “{“ & 
      “loggers: {“ &
         “name: {…}” &
     “}}”;

**Comment by pmderodat** [comment]
> I am not planning on changing anything in GNATCOLL.Traces. There’s no way to improve things that while staying backward compatible, so instead we have a separate package.

Ok. We really need to discuss this new tracing module that you intend to add to GNATCOLL. At this point we don’t want to add new packages to GNATCOLL, let alone a competitor tracing module: that’s one more package for us to maintain while we don’t use it, and it will bring just confusion to users about which tracing module to choose.

We prefer that you create a separate self contained project, that is in time amenable to use in a package manager. We are always happy to see new libraries & efforts related to Ada and open source, so we can help you raise awareness about your library by several ways such as Twitter or eventually a guest blog post if you are interested in such a thing. 

> I am not sure what you call a configuration API.

Let me clarify what I would call a configuration API: today in `GNATCOLL.Traces`, beyond the creation of the various trace objects, the only way to configure logging is through some custom DSL, so with strings in Ada. As you wrote:
```ada
Config : constant String := "…";
Parse_Config (Config);
```
If you want to change anything from here, you have to modify the corresponding text in `Config` and re-run `Parse_Config`. Beyond the `Parse_Config` procedure, there is not much of an Ada API.

Instead of having to deal with strings, you could have instead:
```ada
Global_Config : Global_Traces_Config;
My_Module_Config : Trace_Config := Global_Config.Trace ("MY_MODULE");
My_Module_Config.Enable;
My_Module_Config.Set_Fg_Color ("red");
My_Module_Config.Redirect_To ("my_module.log");
Set_Config (Global_Config);
```
Or another expression-based API to express equivalent configuration:
```ada
Set_Config (Config
  ((1 => Trace_Config ("My_Module", Enabled => True,
                      Fg_Color => “red”,
                      Redirect_To => "my_module.log"))));
```
Either way, it is really a programmatic configuration, where you don’t have to mess with parsing & unparsing in order to configure traces. Once you have this, it’s then super easy to write a configuration front-end, either parsing text from YAML, XML, or even have a graphical widget, except for the meat of the front-end, of course!

This way you don’t have to painfully maintain string literals to embed a DSL in Ada, the way you would with JSON. Also you get compile-time syntax & typing errors for free, which you don’t with string literals to be parsed at runtime.
