### ISSUE TITLE
Gnatcoll on OpenBSD, posix and waitid

### ISSUE THREAD

**Issue by kevlar700** [AdaCore/gnatcoll-core#59]
When building gnatcoll 22.0.0 on OpenBSD with alire.
I find that src/os/unix/process-wrappers.c:147:13 fails as OpenBSD does not implement waitid

Should I see if OpenBSD are open to a waitid patch (FreeBSD and NetBSD have waitid already) or would Gnatcoll be better off using waitpid?

Regards, Kc

**Comment by kevlar700** [comment]
It seems that there is a PR.

https://github.com/AdaCore/gnatcoll-core/pull/57

**Comment by kevlar700** [comment]
@mndrix 
Can you ellaborate on?

"The semantics of Process_State, which leaves a terminated child process in a waitable condition, are not readily achievable on OpenBSD."

**Comment by mndrix** [comment]
> Are you saying that implementing waitID is more complicated for OpenBSD or just currently unimplemented?

Sorry for any confusion. I suppose that OpenBSD kernel developers could implement `waitid` but they haven't, so it's currently unavailable for implementing `Process_State`.  That's why I chose to use `waitpid` in #57.

> Should I see if OpenBSD are open to a waitid patch

I'm not aware of any discussions on the mailing lists suggesting that OpenBSD is opposed to `waitid`, so they might accept a patch.

**Comment by Jicquel** [comment]
Hello @kevlar700, thank you for opening this issue. We apologize for the delay. It seems that `waitid` has been introduced in 2023 (https://www.openbsd.org/73.html). I am closing this issue, but feel free to reopen it if needed!
