### ISSUE TITLE
Simplify code

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/gnatcoll-core#74]
Dear Developers,

The if statement on 
https://github.com/AdaCore/gnatcoll-core/blob/c7abf67e7685734be8f88334f0d0ba409cf8ea1a/src/gnatcoll-opt_parse.adb#L783-L787

can be simplified into

```
return R /= null and then Flag_Parser_Result (R.all).Result;
```

Greetings,
 Pierre

Problem detected and solved by Rejuvenation-Ada crate
[![vote for Rejuvenation-Ada as The 2022 Ada Crate Of The Year](https://user-images.githubusercontent.com/18348654/191469254-1ca1f4a0-6242-43fa-94a2-f39f55817fdc.jpg)](https://github.com/AdaCore/Ada-SPARK-Crate-Of-The-Year/issues/15)

**Comment by t-14** [comment]
Turning it into an expression doesn't help readability.

**Comment by pjljvandelaar** [comment]
Experiments reported in literature disagree with your remark.
```
 if R /= null then 
    return Flag_Parser_Result (R.all).Result; 
 else 
    return False; 
 end if; 
```
has 5 lines and has two branches to consider.
Although one branch is simple (False), it is explicitly present.

```
return R /= null and then Flag_Parser_Result (R.all).Result;
```
is one line, and has two subexpression that are connected with the short circuit operator `and then`.

But it is your code, so your decision.

**Comment by t-14** [comment]
I am not sure which literature you refer to so can't judge how it applies here, but checking if it's a null access and deciding what to return when it is and when it is not are two distinct decisions, and collapsing them into one because "hey it's Booleans everywhere anyway" is something that Ada programmers don't typically do. For argument's sake, imagine we decide tomorrow that function Get no longer returns a Boolean but some other type, and consider the cost of refactoring to do this for the original code and for your rewriting...
